# coding: utf-8

# flake8: noqa
"""
    home-iot-api

    The API for the EatBacon IOT project  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.api_response import ApiResponse
from swagger_client.models.city import City
from swagger_client.models.device_registration_info import DeviceRegistrationInfo
from swagger_client.models.device_state import DeviceState
from swagger_client.models.forecast import Forecast
from swagger_client.models.forecast_response import ForecastResponse
from swagger_client.models.forecast_temperature import ForecastTemperature
from swagger_client.models.heater_state import HeaterState
from swagger_client.models.lighting_summary import LightingSummary
from swagger_client.models.lighting_zone import LightingZone
from swagger_client.models.lighting_zone_status import LightingZoneStatus
from swagger_client.models.temperatue_zone_status import TemperatueZoneStatus
from swagger_client.models.temperature_summary import TemperatureSummary
from swagger_client.models.temperature_zone import TemperatureZone
from swagger_client.models.weather_forecast import WeatherForecast
