# coding: utf-8

"""
    home-iot-api

    The API for the EatBacon IOT project  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class City(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'lat': 'float',
        'lon': 'float',
        'country': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'lat': 'lat',
        'lon': 'lon',
        'country': 'country'
    }

    def __init__(self, id=None, name=None, lat=None, lon=None, country=None):  # noqa: E501
        """City - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._lat = None
        self._lon = None
        self._country = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if lat is not None:
            self.lat = lat
        if lon is not None:
            self.lon = lon
        if country is not None:
            self.country = country

    @property
    def id(self):
        """Gets the id of this City.  # noqa: E501


        :return: The id of this City.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this City.


        :param id: The id of this City.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this City.  # noqa: E501


        :return: The name of this City.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this City.


        :param name: The name of this City.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def lat(self):
        """Gets the lat of this City.  # noqa: E501


        :return: The lat of this City.  # noqa: E501
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat):
        """Sets the lat of this City.


        :param lat: The lat of this City.  # noqa: E501
        :type: float
        """

        self._lat = lat

    @property
    def lon(self):
        """Gets the lon of this City.  # noqa: E501


        :return: The lon of this City.  # noqa: E501
        :rtype: float
        """
        return self._lon

    @lon.setter
    def lon(self, lon):
        """Sets the lon of this City.


        :param lon: The lon of this City.  # noqa: E501
        :type: float
        """

        self._lon = lon

    @property
    def country(self):
        """Gets the country of this City.  # noqa: E501


        :return: The country of this City.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this City.


        :param country: The country of this City.  # noqa: E501
        :type: str
        """

        self._country = country

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(City, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, City):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
