# coding: utf-8

"""
    home-iot-api

    The API for the EatBacon IOT project  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ForecastResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'city': 'City',
        'values': 'list[Forecast]'
    }

    attribute_map = {
        'city': 'city',
        'values': 'values'
    }

    def __init__(self, city=None, values=None):  # noqa: E501
        """ForecastResponse - a model defined in Swagger"""  # noqa: E501
        self._city = None
        self._values = None
        self.discriminator = None
        if city is not None:
            self.city = city
        if values is not None:
            self.values = values

    @property
    def city(self):
        """Gets the city of this ForecastResponse.  # noqa: E501


        :return: The city of this ForecastResponse.  # noqa: E501
        :rtype: City
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this ForecastResponse.


        :param city: The city of this ForecastResponse.  # noqa: E501
        :type: City
        """

        self._city = city

    @property
    def values(self):
        """Gets the values of this ForecastResponse.  # noqa: E501


        :return: The values of this ForecastResponse.  # noqa: E501
        :rtype: list[Forecast]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this ForecastResponse.


        :param values: The values of this ForecastResponse.  # noqa: E501
        :type: list[Forecast]
        """

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ForecastResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ForecastResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
