# coding: utf-8

"""
    home-iot-api

    The API for the EatBacon IOT project  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TemperatueZoneStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'value': 'float',
        'units': 'str',
        'timestamp': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'value': 'value',
        'units': 'units',
        'timestamp': 'timestamp'
    }

    def __init__(self, id=None, name=None, value=None, units='fahrenheit', timestamp=None):  # noqa: E501
        """TemperatueZoneStatus - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._value = None
        self._units = None
        self._timestamp = None
        self.discriminator = None
        self.id = id
        if name is not None:
            self.name = name
        self.value = value
        if units is not None:
            self.units = units
        self.timestamp = timestamp

    @property
    def id(self):
        """Gets the id of this TemperatueZoneStatus.  # noqa: E501

        the unique identifier for the zone  # noqa: E501

        :return: The id of this TemperatueZoneStatus.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TemperatueZoneStatus.

        the unique identifier for the zone  # noqa: E501

        :param id: The id of this TemperatueZoneStatus.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this TemperatueZoneStatus.  # noqa: E501

        the name of the zone  # noqa: E501

        :return: The name of this TemperatueZoneStatus.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TemperatueZoneStatus.

        the name of the zone  # noqa: E501

        :param name: The name of this TemperatueZoneStatus.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def value(self):
        """Gets the value of this TemperatueZoneStatus.  # noqa: E501

        the temperature in the zone  # noqa: E501

        :return: The value of this TemperatueZoneStatus.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this TemperatueZoneStatus.

        the temperature in the zone  # noqa: E501

        :param value: The value of this TemperatueZoneStatus.  # noqa: E501
        :type: float
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def units(self):
        """Gets the units of this TemperatueZoneStatus.  # noqa: E501

        the temperature units  # noqa: E501

        :return: The units of this TemperatueZoneStatus.  # noqa: E501
        :rtype: str
        """
        return self._units

    @units.setter
    def units(self, units):
        """Sets the units of this TemperatueZoneStatus.

        the temperature units  # noqa: E501

        :param units: The units of this TemperatueZoneStatus.  # noqa: E501
        :type: str
        """
        allowed_values = ["celsius", "fahrenheit"]  # noqa: E501
        if units not in allowed_values:
            raise ValueError(
                "Invalid value for `units` ({0}), must be one of {1}"  # noqa: E501
                .format(units, allowed_values)
            )

        self._units = units

    @property
    def timestamp(self):
        """Gets the timestamp of this TemperatueZoneStatus.  # noqa: E501

        the timestamp when the temperature was measured  # noqa: E501

        :return: The timestamp of this TemperatueZoneStatus.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this TemperatueZoneStatus.

        the timestamp when the temperature was measured  # noqa: E501

        :param timestamp: The timestamp of this TemperatueZoneStatus.  # noqa: E501
        :type: datetime
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TemperatueZoneStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TemperatueZoneStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
