# coding: utf-8

"""
    home-iot-api

    The API for the EatBacon IOT project  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.device_api import DeviceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self):
        self.api = DeviceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_devices(self):
        """Test case for get_devices

        """
        pass

    def test_register(self):
        """Test case for register

        """
        pass


if __name__ == '__main__':
    unittest.main()
