# coding: utf-8

"""
    home-iot-api

    The API for the EatBacon IOT project  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.device_state import DeviceState  # noqa: E501
from swagger_client.rest import ApiException


class TestDeviceState(unittest.TestCase):
    """DeviceState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceState(self):
        """Test DeviceState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.device_state.DeviceState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
