# coding: utf-8

"""
    home-iot-api

    The API for the EatBacon IOT project  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.zones_api import ZonesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestZonesApi(unittest.TestCase):
    """ZonesApi unit test stubs"""

    def setUp(self):
        self.api = ZonesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_zones(self):
        """Test case for get_zones

        """
        pass

    def test_quiet_zone(self):
        """Test case for quiet_zone

        """
        pass


if __name__ == '__main__':
    unittest.main()
