# coding: utf-8

"""
    home-iot-api

    The API for the EatBacon IOT project  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.temperature_zone import TemperatureZone  # noqa: E501
from swagger_client.rest import ApiException


class TestTemperatureZone(unittest.TestCase):
    """TemperatureZone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTemperatureZone(self):
        """Test TemperatureZone"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.temperature_zone.TemperatureZone()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
