# coding: utf-8

"""
    home-iot-api

    The API for the EatBacon IOT project  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.weather_forecast import WeatherForecast  # noqa: E501
from swagger_client.rest import ApiException


class TestWeatherForecast(unittest.TestCase):
    """WeatherForecast unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWeatherForecast(self):
        """Test WeatherForecast"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.weather_forecast.WeatherForecast()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
